# Generated by Django 3.0.4 on 2021-06-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='email',
        ),
    ]
