# Generated by Django 3.0.4 on 2021-06-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_club_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='directivo',
        ),
        migrations.RemoveField(
            model_name='club',
            name='estadio',
        ),
        migrations.RemoveField(
            model_name='club',
            name='historia',
        ),
        migrations.RemoveField(
            model_name='club',
            name='mision',
        ),
        migrations.RemoveField(
            model_name='club',
            name='numero_telefono',
        ),
        migrations.RemoveField(
            model_name='club',
            name='red',
        ),
    ]
