# Generated by Django 3.0.4 on 2021-06-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210602_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steam',
            new_name='Equipo',
        ),
        migrations.RemoveField(
            model_name='club',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='club',
            name='imagen',
        ),
    ]
