# Generated by Django 3.0.4 on 2021-06-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210602_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio'),
        ),
        migrations.AddField(
            model_name='club',
            name='directivo',
            field=models.ManyToManyField(blank=True, to='core.Persona'),
        ),
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(default='xxxxx@xxx.com', max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='estadio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estadio'),
        ),
        migrations.AddField(
            model_name='club',
            name='historia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='club',
            name='mision',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='club',
            name='numero_telefono',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Red'),
        ),
    ]
