# Generated by Django 3.0.4 on 2021-06-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('equivo_casa', models.CharField(max_length=50)),
                ('equipo_invitado', models.CharField(max_length=50)),
                ('goles_invitado', models.IntegerField()),
                ('goles_casa', models.IntegerField()),
            ],
        ),
    ]
